# Site settings
title: Hello, Internet Stranger
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "kattkennedy.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Katt Kennedy
user_description: I do practical analysis for businesses. I'm a seasoned data scientist, specializing in early-stage product analytics, dataset rehabilitation, and root cause analysis.  I studied quantitative psychology, business, and computer science, and then worked for over a decade in a variety of data roles.   <br> <br>  You can find out more on my <a href="resume.pdf">resume</a>. 
user_title: Data Scientist
email: katt@fatehold.com
twitter_username: octokatt_bot
github_username:  octokatt

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
