# Site settings
title: Hello, Internet Stranger
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "kattkennedy.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Katt Kennedy
user_description: I do practical analysis for businesses. I've worked with siloed ERP/CRM platforms, time-series survey design, gigabytes of irregularly formatted data, and high-level data architecture and infrastructure design. 
user_title: Data Scientist, MBA
email: katt@fatehold.com
twitter_username: octokatt_bot
github_username:  octokatt

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
